### ISSUE TITLE
Feature request: add a mechanism for authenticated git clones

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle-enterprise-build-validation-scripts#421]
We would like to start running these scripts on a semi-automated basis, which would require giving an auth token and user name to the `git clone` commands. Currently it's not possible, and I'm not currently able to see a way to do this via global credential helper. So, I'd like to feature request the ability to add support for this. We can expose these as arguments, env vars, or however else is most convenient.

**Comment by erichaagdev** [comment]
👋 Hey @ZacSweers!

How do you typically provide credentials to `git clone` in CI? The scripts are just using `git clone`, so your normal mechanism of configuring authentication would apply to the scripts too.

If you do need to supply additional parameters to the `git clone` you can also use the `-o` / `--git-options` parameter.

**Comment by ZacSweers** [comment]
In the setup I'm building, we're using GitHub actions and the actions/checkout action to do the initial clone, which handles passing in relevant authentication arguments to the underlying clone. I'll take a look at git-options 👀

**Comment by erichaagdev** [comment]
Got it. 👌 

Please let us know if that does not work for you. For now, I will close the issue. We can always reopen it if necessary. 

Thank you!

**Comment by ZacSweers** [comment]
Sorry, are there more docs anywhere? The only reference I can find anywhere is this: https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/2ae83a4ed60818ac0ed8e1646fad40ba090bb50a/components/scripts/lib/help.sh#L25

It's unclear what the expected input to that is supposed to be, is this documented somewhere?

**Comment by erichaagdev** [comment]
The `-o` / `--git-options` parameter allows you to pass additional arguments to the underlying `git clone`. The expected input would be any valid `git clone` parameters (for example `-o '--depth=20'`): https://git-scm.com/docs/git-clone

For your original request, I have come up with a way to run the experiments that should work for you. It leverages the fact that we can run the scripts using a local Git repository. This means you can use the existing GitHub actions/checkout action to clone the project. Once the project is cloned, you can specify the local checkout directory as the value of `-r` / `--git-repository`. For example:

```yaml
name: Run Build Validation Scripts

on: [ workflow_dispatch ]

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: project-to-validate # check out the project to a subdirectory
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Download latest version of the validation scripts
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/gradle/download@actions-stable
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run experiment 3
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/gradle/experiment-3@actions-stable
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}"
        with:
          gitRepo: "file://$GITHUB_WORKSPACE/project-to-validate" # use the local checkout
          tasks: build
```

I tested this and was able to successfully run experiments with a private repository (it's public now so you can see it): https://github.com/erichaagdev/test-build-validation-private-repo/actions/runs/4826577565

The above sample uses [our composite workflows](https://github.com/gradle/gradle-enterprise-build-validation-scripts/tree/main/.github/actions/gradle) to download and execute the experiments, but they aren't required. 

If you're looking for inspiration, we have our [gradle/gradle-enterprise-oss-projects](https://github.com/gradle/gradle-enterprise-oss-projects/tree/main/.github/workflows) repository where we automate these experiments for our open-source partners.
